# Generated by Django 3.1.1 on 2020-09-21 21:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('website', models.URLField(blank=True, verbose_name='URL site internet')),
                ('tagline', models.CharField(blank=True, max_length=255, verbose_name='Brève description')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Logo')),
            ],
            options={
                'verbose_name': 'Entreprise',
                'verbose_name_plural': 'Entreprises',
            },
        ),
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('name', models.CharField(max_length=50, verbose_name='Nom')),
            ],
            options={
                'verbose_name': "Catégorie d'emploi",
                'verbose_name_plural': "Catégories d'emplois",
            },
        ),
        migrations.CreateModel(
            name='JobType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('name', models.CharField(max_length=50, verbose_name='Nom')),
            ],
            options={
                'verbose_name': "Type d'emploi",
                'verbose_name_plural': "Types d'emplois",
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('pro_title', models.CharField(max_length=200, verbose_name='Titre professionel')),
                ('location', models.CharField(max_length=150, verbose_name='Lieu de résidence')),
                ('website', models.URLField(blank=True, verbose_name='Lien du portfolio')),
                ('resume_file', models.FileField(upload_to='resumes', verbose_name='Fichier CV')),
                ('description', models.TextField(verbose_name='A propos de vous')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name="Lieu d'execution")),
                ('tags', models.CharField(blank=True, max_length=255, verbose_name='Tags')),
                ('description', models.TextField(verbose_name='Description du poste')),
                ('application_email', models.EmailField(max_length=254, verbose_name='Adresse email de postulat')),
                ('closing_date', models.DateField(blank=True, null=True, verbose_name='Date de fermeture')),
                ('category', models.ManyToManyField(to='jobs.JobCategory', verbose_name='Catégorie')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.company', verbose_name='Entreprise')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.jobtype', verbose_name='Type')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to=settings.AUTH_USER_MODEL, verbose_name='Créateur')),
            ],
            options={
                'verbose_name': "Offre d'emploi",
                'verbose_name_plural': "Offres d'emplois",
            },
        ),
    ]
