# Generated by Django 3.1.1 on 2020-09-22 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='contact',
            field=models.CharField(default='', help_text='Aidez les récruteurs à vous contacter', max_length=255, verbose_name='Votre contact'),
            preserve_default=False,
        ),
    ]
