# Generated by Django 3.1.1 on 2020-09-15 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='description',
            field=models.TextField(blank=True, verbose_name='A propos de vous'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='resume_file',
            field=models.FileField(blank=True, upload_to='', verbose_name='Fichier CV'),
        ),
    ]
