# Generated by Django 3.1.1 on 2020-09-22 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_resume_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='tags',
        ),
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.ManyToManyField(to='jobs.JobCategory', verbose_name="Secteur d'emploi"),
        ),
    ]
