# Generated by Django 3.1.1 on 2020-09-23 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20200922_2303'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobcategory',
            options={'verbose_name': "Secteur d'emploi", 'verbose_name_plural': "Secteurs d'emplois"},
        ),
        migrations.AddField(
            model_name='jobcategory',
            name='linear_icon',
            field=models.CharField(default='ln-icon-Bar-Chart', max_length=50, verbose_name='Icon'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.ManyToManyField(related_name='jobs', to='jobs.JobCategory', verbose_name="Secteur d'emploi"),
        ),
    ]
