# Generated by Django 3.1.1 on 2020-09-15 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20200915_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='resume_file',
            field=models.FileField(blank=True, upload_to='resumes', verbose_name='Fichier CV'),
        ),
    ]
