# Generated by Django 3.1.1 on 2020-09-26 21:37

from django.db import migrations, models
import genoskul.common.validators


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_auto_20200923_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='', validators=[genoskul.common.validators.file_size], verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='resume_file',
            field=models.FileField(upload_to='resumes', validators=[genoskul.common.validators.file_size], verbose_name='Fichier CV'),
        ),
    ]
