# Generated by Django 3.1.1 on 2020-09-19 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_auto_20200918_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='website',
            field=models.URLField(blank=True, verbose_name='Lien du portfolio'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='description',
            field=models.TextField(verbose_name='A propos de vous'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='resume_file',
            field=models.FileField(upload_to='resumes', verbose_name='Fichier CV'),
        ),
    ]
