# Generated by Django 3.1.1 on 2021-01-29 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_auto_20210129_1603'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ('-created_at',)},
        ),
    ]
