# Generated by Django 3.1.1 on 2021-02-10 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_auto_20210129_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='visibility',
            field=models.CharField(choices=[('private', 'Privé'), ('public', 'Public')], default='private', max_length=20, verbose_name='Visibilité'),
        ),
        migrations.AlterField(
            model_name='forum',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nom du forum'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='detail',
            field=models.TextField(verbose_name='Commentaire'),
        ),
    ]
