# Generated by Django 3.1.1 on 2021-02-11 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_auto_20210210_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumregistration',
            name='date',
            field=models.DateField(auto_now=True, verbose_name="Date d'inscription au forum"),
        ),
    ]
