# Generated by Django 3.1.1 on 2020-09-24 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BoxType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('name', models.CharField(max_length=150, verbose_name='Nom du type')),
            ],
            options={
                'verbose_name': 'Type de service',
                'verbose_name_plural': 'Types de services',
            },
        ),
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('struct_name', models.CharField(max_length=150, verbose_name='Nom de la structure')),
                ('struct_description', models.TextField(verbose_name='Description de la structure')),
                ('activity_description', models.TextField(verbose_name='Description des activités')),
                ('address', models.CharField(help_text='Quartier/Ville/Pays', max_length=100, verbose_name='Adresse de localisation')),
                ('contact', models.CharField(max_length=50, verbose_name='Contact')),
                ('logo', models.ImageField(upload_to='', verbose_name='Logo de la boite')),
                ('detail_link', models.URLField(verbose_name='Lien')),
                ('confirmed', models.BooleanField(default=False, verbose_name='Confirmé ?')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to=settings.AUTH_USER_MODEL)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='services.boxtype', verbose_name='Type de service')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
