# Generated by Django 3.1.1 on 2020-09-23 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('type', models.CharField(max_length=150, verbose_name='Type')),
                ('struct_name', models.CharField(max_length=150, verbose_name='Nom de la structure')),
                ('struct_description', models.TextField(verbose_name='Description de la structure')),
                ('activity_description', models.TextField(verbose_name='Description des activités')),
                ('address', models.CharField(help_text='Quartier/Ville/Pays', max_length=100, verbose_name='Adresse de localisation')),
                ('contact', models.CharField(max_length=50, verbose_name='Contact')),
                ('logo', models.ImageField(upload_to='', verbose_name='Logo de la boite')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
