# Generated by Django 3.1.1 on 2020-10-02 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20200926_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='confirmed',
            field=models.BooleanField(default=True, verbose_name='Confirmé ?'),
        ),
    ]
