# Generated by Django 3.1.1 on 2020-10-03 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20201003_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='confirmed',
            field=models.BooleanField(default=False, verbose_name='Confirmé ?'),
        ),
    ]
