# Generated by Django 3.1.1 on 2020-10-06 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_auto_20201003_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='activity_description',
            field=models.TextField(help_text="Qu'est ce que vous et/ou votre structure faites?", verbose_name='Description des activités'),
        ),
        migrations.AlterField(
            model_name='box',
            name='detail_link',
            field=models.URLField(help_text='lien du site de votre structure ou de votre page', verbose_name='Lien'),
        ),
        migrations.AlterField(
            model_name='box',
            name='struct_description',
            field=models.TextField(help_text="Biographie si c'est une personne", verbose_name='Description de la structure'),
        ),
        migrations.AlterField(
            model_name='box',
            name='struct_name',
            field=models.CharField(help_text="Nom &  prenoms si c'est une personne", max_length=150, verbose_name='Nom de la structure'),
        ),
    ]
