# Generated by Django 3.1.1 on 2020-11-06 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_auto_20201006_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='contact',
            field=models.CharField(help_text='adress mail ou numero whatsapp', max_length=50, verbose_name='Contact'),
        ),
    ]
