# Generated by Django 3.1.1 on 2020-09-19 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='function',
            field=models.CharField(blank=True, choices=[('eleve', 'Elève'), ('student', 'Etudiant'), ('unemployed', 'Diplomé sans emploi'), ('employed', 'Fonctionnaire'), ('entrepreneur', 'Entrepreneur'), ('other', 'Autres')], max_length=100, verbose_name='Fonction'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Masculin'), ('female', 'Feminin')], max_length=10, verbose_name='Genre'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='residence',
            field=models.CharField(blank=True, max_length=50, verbose_name='Lieu de résidence'),
        ),
    ]
