# Generated by Django 3.1.1 on 2020-09-26 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ndjor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name': 'Catégorie de produit', 'verbose_name_plural': 'Catégories des produits'},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='categories',
            new_name='category',
        ),
    ]
