# Generated by Django 3.1.1 on 2020-09-26 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ndjor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to='', verbose_name='Photo de produit'),
        ),
    ]
