# Generated by Django 3.1.1 on 2020-09-26 21:37

from django.db import migrations, models
import genoskul.common.validators


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='', validators=[genoskul.common.validators.file_size], verbose_name='Fichier'),
        ),
    ]
