# Generated by Django 3.1.1 on 2020-12-20 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='categories',
            field=models.ManyToManyField(help_text='Appuyez sur «Ctrl» pour sélectionner plusieurs', related_name='documents', to='learning.DocumentCategory', verbose_name='Catégories'),
        ),
    ]
