# Generated by Django 3.1.1 on 2020-09-13 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='category',
            new_name='categories',
        ),
    ]
