# Generated by Django 3.1.1 on 2020-10-03 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_auto_20200926_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='categories',
            field=models.ManyToManyField(help_text='Appuyez sur «Ctrl» pour sélectionner plusieurs', related_name='learning', to='learning.DocumentCategory', verbose_name='Catégories'),
        ),
    ]
