# Generated by Django 3.1.1 on 2020-10-06 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_auto_20201003_2216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='description',
        ),
        migrations.AddField(
            model_name='document',
            name='auteur',
            field=models.TextField(blank=True, verbose_name='Auteur du document'),
        ),
    ]
