# Generated by Django 3.1.1 on 2020-09-14 17:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learning', '0003_auto_20200913_2147'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentcategory',
            options={'verbose_name': 'Catégorie de document', 'verbose_name_plural': 'Catégories de document'},
        ),
        migrations.AlterModelOptions(
            name='documenttype',
            options={'verbose_name': 'Type de document', 'verbose_name_plural': 'Types de documents'},
        ),
        migrations.AlterField(
            model_name='document',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL, verbose_name='Créateur'),
        ),
    ]
