# Generated by Django 3.1.1 on 2020-09-15 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_auto_20200914_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='download_count',
            field=models.IntegerField(blank=True, default=0, verbose_name='Nombre de téléchargements'),
        ),
    ]
