# Generated by Django 3.1.1 on 2021-02-11 12:44

from django.db import migrations, models
import tinymce_4.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('content', tinymce_4.fields.TinyMCEModelField(verbose_name='Content')),
            ],
            options={
                'verbose_name': 'A propos',
                'verbose_name_plural': 'A propos',
            },
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('content', models.TextField(verbose_name='Petite de description du pied de page')),
            ],
            options={
                'verbose_name': 'Pied de page',
                'verbose_name_plural': 'Pieds de page',
            },
        ),
        migrations.CreateModel(
            name='Privacy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('content', tinymce_4.fields.TinyMCEModelField(verbose_name='Content')),
            ],
            options={
                'verbose_name': 'Politique de confidentialité',
                'verbose_name_plural': 'Politiques de confidentialité',
            },
        ),
        migrations.CreateModel(
            name='SocialNetwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('name', models.CharField(max_length=20, verbose_name='Nom du réseau social')),
                ('type', models.CharField(choices=[('facebook', 'Facebook'), ('whatsapp', 'Whatsapp'), ('telegram', 'Telegram'), ('linkedin', 'LinkedIn'), ('envelope', 'Gmail')], max_length=10, verbose_name='Type du réseau')),
                ('link', models.URLField(verbose_name='Lien direct du réseau social')),
            ],
            options={
                'verbose_name': 'Réseau Social',
                'verbose_name_plural': 'Résaux sociaux',
            },
        ),
        migrations.CreateModel(
            name='TermOfService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('content', tinymce_4.fields.TinyMCEModelField(verbose_name='Content')),
            ],
            options={
                'verbose_name': 'Terme de serice',
                'verbose_name_plural': 'Termes de serice',
            },
        ),
    ]
