# Generated by Django 3.1.1 on 2020-09-24 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('us', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('content', models.TextField(verbose_name='Petite de description du pied de page')),
            ],
            options={
                'verbose_name': 'Pied de page',
                'verbose_name_plural': 'Pieds de page',
            },
        ),
    ]
