# Generated by Django 3.1.1 on 2020-09-24 16:49

from django.db import migrations, models
import tinymce_4.fields


class Migration(migrations.Migration):

    dependencies = [
        ('us', '0002_footer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Privacy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('content', tinymce_4.fields.TinyMCEModelField(verbose_name='Content')),
            ],
            options={
                'verbose_name': 'Politique de confidentialité',
                'verbose_name_plural': 'Politiques de confidentialité',
            },
        ),
        migrations.CreateModel(
            name='TermOfService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('content', tinymce_4.fields.TinyMCEModelField(verbose_name='Content')),
            ],
            options={
                'verbose_name': 'Terme de serice',
                'verbose_name_plural': 'Termes de serice',
            },
        ),
    ]
