# Generated by Django 3.1.1 on 2020-09-24 19:40

from django.db import migrations, models
import tinymce_4.fields


class Migration(migrations.Migration):

    dependencies = [
        ('us', '0003_privacy_termofservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('content', tinymce_4.fields.TinyMCEModelField(verbose_name='Content')),
            ],
            options={
                'verbose_name': 'A propos',
                'verbose_name_plural': 'A propos',
            },
        ),
    ]
